on:
  issues:
    types:
      - opened
jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '16'
      - name: Clonage du script
        uses: actions/checkout@master
        with:
          repository: EarthNetwork/discord-status-webhook
      - name: Installation des deps
        run: npm ci
      - name: Exécution du script
        run: node .
        env:
          issueTitle: ${{ github.event.issue.title }}
          discordUrl: ${{ secrets.discordUrl }}
          back: false
